# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-22 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proxy_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.CharField(max_length=64, null=True)),
                ('proxy_name', models.CharField(max_length=128, null=True)),
                ('protocol', models.BooleanField(default=False)),
                ('listen', models.IntegerField()),
                ('server_name', models.CharField(max_length=128, null=True)),
                ('access_log', models.CharField(max_length=128, null=True)),
                ('error_log', models.CharField(max_length=128, null=True)),
                ('to_domain_toggle', models.BooleanField(default=False)),
                ('to_domain', models.CharField(max_length=128, null=True)),
                ('balancer_type', models.CharField(max_length=64, null=True)),
                ('http_check', models.BooleanField(default=False)),
                ('gzip', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('ssl', models.BooleanField(default=False)),
                ('ssl_http2', models.BooleanField(default=False)),
                ('ssl_redirect_https', models.BooleanField(default=False)),
                ('ssl_cert', models.TextField(null=True)),
                ('ssl_cert_path', models.CharField(max_length=128, null=True)),
                ('ssl_key', models.TextField(null=True)),
                ('ssl_key_path', models.CharField(max_length=128, null=True)),
                ('custom_config', models.TextField(null=True)),
                ('backend_protocol', models.CharField(max_length=64, null=True)),
                ('backend_domain_toggle', models.BooleanField(default=False)),
                ('backend_domain', models.CharField(max_length=128, null=True)),
                ('host', models.CharField(max_length=64, null=True)),
                ('status', models.BooleanField(default=False)),
                ('update_time', models.FloatField()),
                ('max_fails', models.IntegerField(default=5)),
                ('fail_timeout', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='upstream_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=64)),
                ('port', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='proxy_config',
            name='upstream_list',
            field=models.ManyToManyField(to='proxy.upstream_config'),
        ),
    ]
