# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proxy_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.CharField(max_length=64, null=True)),
                ('protocols', models.BooleanField()),
                ('proxy_name', models.CharField(max_length=128, null=True)),
                ('status', models.BooleanField()),
                ('listen', models.IntegerField()),
                ('service_name', models.CharField(max_length=128, null=True)),
                ('access_log', models.CharField(max_length=128, null=True)),
                ('error_log', models.CharField(max_length=128, null=True)),
                ('ssl_cert', models.CharField(max_length=32)),
                ('ssl_key', models.CharField(max_length=32)),
                ('update_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='upstream_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('balancer_type', models.CharField(max_length=64, null=True)),
                ('address', models.CharField(max_length=64, null=True)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='proxy_config',
            name='upstream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy.upstream_config'),
        ),
    ]
