# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_auto_20160712_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy_config',
            name='upstream',
        ),
        migrations.AddField(
            model_name='upstream_config',
            name='proxy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='proxy.proxy_config'),
            preserve_default=False,
        ),
    ]
