# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0005_auto_20160713_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxy_config',
            old_name='service_name',
            new_name='server_name',
        ),
    ]
