# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0006_auto_20160713_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upstream_config',
            name='proxy',
        ),
        migrations.AddField(
            model_name='proxy_config',
            name='upstream_list',
            field=models.ManyToManyField(to='proxy.upstream_config'),
        ),
    ]
