# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0008_auto_20160714_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy_config',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
