# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0009_proxy_config_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy_config',
            name='ssl_cert_path',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='proxy_config',
            name='ssl_key_path',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
