# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='system_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_nic', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
