# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-22 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.CharField(max_length=64, null=True)),
                ('worker_processes', models.IntegerField()),
                ('worker_connections', models.IntegerField()),
                ('keepalive_timeout', models.IntegerField()),
                ('client_max_body_size', models.IntegerField()),
                ('ignore_invalid_headers', models.BooleanField(default=False)),
                ('access_log', models.CharField(max_length=128, null=True)),
                ('error_log', models.CharField(max_length=128, null=True)),
                ('update_time', models.FloatField()),
            ],
        ),
    ]
