# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('worker_processes', models.IntegerField()),
                ('worker_connections', models.IntegerField()),
                ('keepalive_timeout', models.IntegerField()),
                ('client_max_body_size', models.CharField(max_length=16)),
                ('access_log', models.CharField(max_length=128, null=True)),
                ('error_log', models.CharField(max_length=128, null=True)),
                ('update_time', models.FloatField()),
            ],
        ),
    ]
